name: 02-workflow-events.yaml

on:
    pull_request:
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger branch
              run: echo "I have successfully triggered by ${{github.event_name}}"
