name: 05-1-filters-activity-types.yaml
on:
    pull_request:
        types: [opened, synchronize]
        branches: main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: message print
              run: echo "Running whenever a PR is open or synchronized AND base branch  main"
